jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set submission metadata
      env:
        PR_DATE: ${{ github.event.pull_request.created_at }}
        # Fallback if the event is a push rather than a PR
      run: |
        if [ -z "$PR_DATE" ]; then
          PR_DATE=$(git log -1 --format='%ad' --date=short)
        fi
        echo "SUBMIT_DATE=$PR_DATE" >> $GITHUB_ENV

    - name: Evaluate & append to CSV
      run: |
        python3 scripts/evaluate_submission.py \
          --submission-path "$SUBMISSION_PATH" \
          --date "$SUBMIT_DATE"
