name: Build & Deploy Leaderboard

on:
  # rebuild the page only when the data or rendering code changes
  push:
    branches: [main]
    paths:
      - "data/results.csv"
      - "scripts/build_leaderboard.py"
      - "templates/**"
  workflow_dispatch:        # manual re-build button in the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: pip

    - run: pip install pandas jinja2

    - name: Build static HTML
      run: python3 scripts/build_leaderboard.py

    # —— deploy ————————————————————————————————
    # Keep this step if you selected **Branch: gh-pages** in
    # Settings → Pages.  (Change publish_dir if you renamed /docs.)
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
