name: Build & Commit Leaderboard

concurrency: leaderboard-build

on:
  push:
    branches: [main]
    paths:
      - "data/results.csv"
      - "scripts/build_leaderboard.py"
      - "templates/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: pip

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Build static HTML
      run: python3 scripts/build_leaderboard.py

    # Commit the freshly generated docs/ back to main
    - name: Commit updated docs
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "CI: rebuild leaderboard"
        file_pattern: docs/index.html
